version: "3.2"
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile.prod
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    env_file:
      - .env


  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata:
