name: CI

on: [push]

jobs:
  build_api:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker image build -t st-retrospect-api -f ./docker/Dockerfile.prod .

      - name: Push to Docker hub
        if: github.ref == 'refs/heads/stage'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker tag st-retrospect-api dhcenter/st-retrospect-api:stage
          docker push dhcenter/st-retrospect-api:stage
          docker logout

      - name: Deploy
        if: github.ref == 'refs/heads/stage'
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: cd st-retrospect-api-stage/ && ./deploy.sh
          host: ${{ secrets.SERVER_HOST }}
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY}}

